# Usage: conda env create --file=environment.yml
name: resnets
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - numpy=1.14.5
  - pillow=5.1.0
  - pip=10.0.1
  - python=3.6.5
  - pytorch=0.4.0
  - tensorboard=1.8.0
  - tensorboardx=1.2
  - tensorflow=1.8.0
  - torchvision=0.2.1
  - tqdm=4.23.4
